#!/usr/bin/env bash

install_arch() {
  install_via_os_default
}
install_mac() {
  install_via_os_default
}
setting_common() {
  tips
}
tips() {
  cat <<'EOF' | inki

- 特定の置き場を信頼する。
  - ~/.config/direnv/direnv.toml
    ```toml
    [whitelist]
    prefix = [
      "/path/to/your/repo-1",
      "/path/to/your/repo-2",
    ]
    ```
EOF
}
