#!/usr/bin/env bash

install_common() {
  platform=$(get_platform)
  arch=$(get_arch)
  # https://github.com/cli/cli/releases/download/v2.92.0/gh_2.92.0_linux_arm64.tar.gz
  dl_gh_release cli/cli latest "*${platform}_${arch}.tar.gz"
  exe 'tar -xzf gh*.tar.gz'
  exe 'sudo cp gh*/bin/gh /usr/local/bin/'
}
# install_common() {
#   if ! has go; then
#     log "golang not installed."
#     return
#   fi
#   # Not work
#   exe go install github.com/cli/cli/cmd/gh@latest
# }
# install_arch_by_snap() {
#   if ! has snap; then
#     log "No snap command exist. install snap first." 1>&2
#     return
#   fi
#   exe sudo snap install gh --edge
# }
install_arch() {
  # NOTE: install latest `gh` command via `gh` command.
  # - yay install gh command to /usr/bin
  # - dl_gh_release install gh command to /usr/local/bin
  # - /usr/local/bin is higher priority than /usr/bin, so dl_gh_release is used to install latest version.
  def_install github-cli
  # install_common
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  install_via_os_default
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
# setting_common() {
#   if grep 'gh completion -s zsh' ~/.works.zsh >&/dev/null; then
#     return
#   fi
#   exe "echo 'eval \"\$(gh completion -s zsh)\"' >> ~/.works.zsh"
# }
# setting_arch() { not_supported; }
# setting_msys() { not_supported; }
# setting_cygwin() { not_supported; }
# setting_mac() { not_supported; }
# setting_ubuntu() { not_supported; }
# setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
